name: Release Version after Tag

on:
  push:
    tags:
      - v*

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Build jpackage artifact
        run: ./mvnw clean install
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.ref }}
          tag_name: ${{ github.ref }}
          body_path: README.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload jpackage artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/jpackage/aramis_1.0-1_amd64.deb
          asset_name: aramis_amd64.deb
          asset_content_type: application/vnd.debian.binary-package
